from __future__ import annotations

# Keep these structures stable: tests and profile wiring depend on them.
NUMERIC_CONTROLS: list[tuple[str, float, float]] = [
    ("max_ground_speed", 3.0, 40.0),
    ("run_t90", 0.03, 1.20),
    ("ground_stop_t90", 0.03, 1.20),
    ("air_speed_mult", 0.50, 4.00),
    ("air_gain_t90", 0.03, 1.20),
    ("wallrun_sink_t90", 0.03, 1.20),
    ("jump_height", 0.2, 4.0),
    ("jump_apex_time", 0.08, 1.20),
    ("grace_period", 0.0, 0.35),
    ("camera_base_fov", 70.0, 125.0),
    ("camera_speed_fov_max_add", 0.0, 30.0),
    ("camera_tilt_gain", 0.0, 2.5),
    ("camera_event_gain", 0.0, 3.0),
    ("slide_stop_t90", 0.10, 8.00),
    ("vault_max_ledge_height", 0.40, 7.50),
    ("vault_height_boost", 0.00, 1.20),
    ("vault_forward_boost", 0.00, 4.00),
    ("noclip_speed", 1.0, 80.0),
    ("player_half_height", 0.70, 1.60),
]

TOGGLE_CONTROLS: list[str] = [
    "autojump_enabled",
    "coyote_buffer_enabled",
    "custom_friction_enabled",
    "slide_enabled",
    "vault_enabled",
    "wallrun_enabled",
    "camera_feedback_enabled",
    "harness_camera_smoothing_enabled",
    "harness_animation_root_motion_enabled",
    "character_scale_lock_enabled",
    "surf_enabled",
]

GROUPS: list[tuple[str, list[str], list[str]]] = [
    (
        "Movement Core",
        [
            "max_ground_speed",
            "run_t90",
            "ground_stop_t90",
            "air_speed_mult",
            "air_gain_t90",
            "wallrun_sink_t90",
            "jump_height",
            "jump_apex_time",
            "grace_period",
            "slide_stop_t90",
            "vault_max_ledge_height",
            "vault_height_boost",
            "vault_forward_boost",
            "noclip_speed",
        ],
        [
            "autojump_enabled",
            "coyote_buffer_enabled",
            "slide_enabled",
            "vault_enabled",
            "custom_friction_enabled",
            "wallrun_enabled",
        ],
    ),
    (
        "Camera",
        [
            "camera_base_fov",
            "camera_speed_fov_max_add",
            "camera_tilt_gain",
            "camera_event_gain",
        ],
        [
            "camera_feedback_enabled",
            "harness_camera_smoothing_enabled",
            "harness_animation_root_motion_enabled",
        ],
    ),
    (
        "Surf",
        [],
        ["surf_enabled"],
    ),
    (
        "Character",
        [
            "player_half_height",
        ],
        [
            "character_scale_lock_enabled",
        ],
    ),
]

FIELD_LABELS: dict[str, str] = {
    "max_ground_speed": "Vmax (u/s)",
    "run_t90": "run t90 (s)",
    "ground_stop_t90": "ground stop t90 (s)",
    "air_speed_mult": "air speed multiplier",
    "air_gain_t90": "air gain t90 (s)",
    "wallrun_sink_t90": "wallrun sink t90 (s)",
    "jump_height": "jump height (u)",
    "jump_apex_time": "jump apex time (s)",
    "grace_period": "grace period (s)",
    "camera_base_fov": "camera base fov (deg)",
    "camera_speed_fov_max_add": "camera speed fov max add (deg)",
    "camera_tilt_gain": "camera tilt gain",
    "camera_event_gain": "camera event gain",
    "slide_stop_t90": "slide stop t90 (s)",
    "vault_max_ledge_height": "vault max obstacle height (u)",
    "vault_height_boost": "vault height boost (u/s)",
    "vault_forward_boost": "vault speed boost (u/s)",
    "noclip_speed": "noclip speed (u/s)",
    "player_half_height": "player half height (u)",
}

FIELD_HELP: dict[str, str] = {
    "max_ground_speed": "Lower: lower target run speed. Higher: higher target run speed under held input.",
    "run_t90": "Lower: snappier exponential run response. Higher: slower convergence to target speed.",
    "ground_stop_t90": "Lower: faster slowdown when coasting on ground. Higher: longer inertia before coming to rest.",
    "air_speed_mult": "Lower: tighter air-speed cap relative to Vmax. Higher: allows more carry and bhop top speed.",
    "air_gain_t90": "Lower: faster air speed gain (stronger bhop/strafe gain). Higher: slower air speed build-up.",
    "wallrun_sink_t90": "Lower: weaker wallrun hold and faster height loss. Higher: stronger wallrun hold and slower height loss.",
    "jump_height": "Lower: shorter hop height. Higher: higher jump apex.",
    "jump_apex_time": "Lower: shorter time to jump apex (snappier pop). Higher: longer float to apex.",
    "grace_period": "Lower: tighter shared leniency distance for jump buffer/coyote/vault timing. Higher: wider distance-derived grace window (time scales from speed, but never below base).",
    "camera_base_fov": "Lower: narrower default first-person framing. Higher: wider baseline field of view.",
    "camera_speed_fov_max_add": "Lower: smaller maximum FOV widening above Vmax. Higher: larger maximum widening. No speed FOV applies at or below Vmax; max add is reached around 10x Vmax.",
    "camera_tilt_gain": "Lower: less movement/wallrun/vault camera tilt. Higher: stronger responsive tilt from the same motion states.",
    "camera_event_gain": "Lower: weaker event pulse response (landing + successful bhop). Higher: stronger shared event pulse amplitude.",
    "slide_stop_t90": "Lower: slide momentum bleeds faster on ground. Higher: slide preserves carried speed longer before decelerating.",
    "vault_max_ledge_height": "Lower: only low obstacles can be vaulted. Higher: taller obstacles remain vaultable (up to 3x previous height cap).",
    "vault_height_boost": "Lower: flatter/lower vault arc. Higher: more vertical clearance and stronger vault pop.",
    "vault_forward_boost": "Lower: weaker forward carry when vault triggers. Higher: stronger forward push while vaulting.",
    "noclip_speed": "Lower: slower noclip traversal while flying. Higher: faster noclip speed along view direction.",
    "player_half_height": "Lower: shorter player hull. Higher: taller player hull; eye height auto-scales to keep camera proportion.",
    "autojump_enabled": "Lower (OFF): jump requires press timing each hop. Higher (ON): holding jump auto-queues grounded hops.",
    "coyote_buffer_enabled": "Lower (OFF): disable coyote + buffered leniency windows. Higher (ON): enable forgiving jump windows.",
    "custom_friction_enabled": "Lower (OFF): skip custom ground friction for isolation tests. Higher (ON): use normal friction model.",
    "slide_enabled": "Lower (OFF): shift slide action disabled. Higher (ON): shift engages powerslide with low profile hull.",
    "vault_enabled": "Lower (OFF): disable vault trigger checks. Higher (ON): jump near front ledges can convert into vault clearance.",
    "character_scale_lock_enabled": "Lower (OFF): radius/step stay independent. Higher (ON): radius+step auto-derive from player half height.",
    "wallrun_enabled": "Lower (OFF): wallrun behavior disabled. Higher (ON): run along valid wall contacts with camera tilt + wallrun jump behavior.",
    "camera_feedback_enabled": "Lower (OFF): disable speed/landing/bhop camera feedback layer. Higher (ON): enable read-only camera feedback effects.",
    "surf_enabled": "Lower (OFF): disable surf behavior entirely. Higher (ON): enable surf logic on surfable ramp normals.",
    "harness_camera_smoothing_enabled": "Lower (OFF): disable camera smoothing in harness mode. Higher (ON): enable camera smoothing.",
    "harness_animation_root_motion_enabled": "Lower (OFF): disable animation/root-motion influence. Higher (ON): enable animation/root-motion influence.",
}
